// Builds src/evaluators/names/names-data.js from Heer & Stone's c3 color-naming
// model (https://github.com/StanfordHCI/c3, data/xkcd/c3_data.json).
//
//   node bench/buildNameData.js path/to/c3_data.json
//
// The model records, for each of 8,325 CIELAB voxels, how many xkcd survey
// participants gave it each of 153 color terms. Name difference between two
// colors is 1 - cosine(count vectors), so only each voxel's direction matters.
// Terms carrying less than 2% of a voxel's unit vector are dropped: that keeps
// a quarter of the nonzero counts, and on 20,000 random voxel pairs changes the
// cosine by 0.0016 on average and 0.04 at most.
//
// Encoding: voxels in c3 order (the same order as saliencies.js, which the
// evaluator uses for its L,a,b -> index lookup), separated by '|'. Within a
// voxel, terms are sorted by index and written as (gap since previous index,
// count), each as a base64 varint: 5 value bits per character, high bit set on
// every character except the last.

import fs from 'node:fs';

const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
const THRESHOLD = 0.02;

const varint = (value) => {
    let out = '';
    do {
        const chunk = value & 31;
        value >>= 5;
        out += B64[value > 0 ? chunk | 32 : chunk];
    } while (value > 0);
    return out;
};

const [inputPath] = process.argv.slice(2);
if (!inputPath) {
    console.error('usage: node bench/buildNameData.js path/to/c3_data.json');
    process.exit(1);
}

const c3 = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
const termCount = c3.terms.length;
const voxelCount = c3.color.length / 3;
const counts = Array.from({ length: voxelCount }, () => new Map());
for (let i = 0; i < c3.T.length; i += 2) {
    const index = c3.T[i];
    counts[Math.floor(index / termCount)].set(index % termCount, c3.T[i + 1]);
}

let kept = 0;
let total = 0;
const voxels = counts.map((terms) => {
    const norm = Math.sqrt([...terms.values()].reduce((sum, v) => sum + v * v, 0));
    const entries = [...terms].filter(([, v]) => v / norm >= THRESHOLD).sort((a, b) => a[0] - b[0]);
    total += terms.size;
    kept += entries.length;
    let previous = -1;
    return entries
        .map(([term, count]) => {
            const gap = term - previous - 1;
            previous = term;
            return varint(gap) + varint(count);
        })
        .join('');
});

const source = `// Heer & Stone's color-naming counts for the same 8,325 lab65 voxels as
// saliencies.js, in the same order. Generated by bench/buildNameData.js; see
// that file for the encoding and the 2% truncation it applies.
export const terms = ${JSON.stringify(c3.terms)};
export default "${voxels.join('|')}";
`;

const outputPath = new URL('../src/evaluators/names/names-data.js', import.meta.url);
fs.writeFileSync(outputPath, source);
console.log(`kept ${kept} of ${total} counts; wrote ${(source.length / 1024).toFixed(0)} kB`);
